---
- name: create GCP network
  google.cloud.gcp_compute_network:
    name: network-{{ cluster_name2 }}
    auto_create_subnetworks: 'true'
    project: "{{ project_id }}"
    auth_kind: serviceaccount
    service_account_file: "{{ credentials_file }}"
    state: present
  register: network