apiVersion: v1
kind: Pod
metadata:
   name: kubectl-pod
   labels:
     app: kubectl-pod
spec:
   containers:
   - name: kubectl-pod
     image: pjdsgrouping/kubectl-pod:latest
     ports:
     - containerPort: 5001