apiVersion: apps/v1
kind: Deployment
metadata:
   name: kubectl-pod
   labels:
     app: kubectl-pod
spec:
   replicas: 1
   selector:
      matchLabels:
         app: kubectl-pod
   template:
      metadata:
         labels:
           app: kubectl-pod
      spec:
         containers:
         - name: kubectl-pod
           image: pjdsgrouping/kubectl-gcloud-pod:latest
           env:
           - name: cluster
             value: "cluster-victor"
           - name: zone
             value: "europe-west1-c"
           ports:
           - containerPort: 5001
