apiVersion: v1
kind: Service
metadata:
  name: cluster-app-service
spec:
  type: LoadBalancer
  selector:
    app: cluster-app
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000