- name: echo state
  debug: msg="Deleting instance {{ passed_vm_name }}"

- name: delete an instance
  gcp_compute_instance:
    state: absent
    name: "{{ passed_vm_name }}"
    machine_type: n1-standard-1
    zone: "{{ zone }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    scopes:
    - https://www.googleapis.com/auth/compute