- name: Pull faasd
  git:
    repo: 'https://github.com/openfaas/faasd.git'
    dest: /srv/faasd/

- name: Install faasd
  command: sh /srv/faasd/hack/install.sh

- name: Restart faasd because of known bug
  systemd:
    state: restarted
    daemon_reload: yes
    name: faasd