- name: Create an instance
  hosts: localhost
  gather_facts: no
  vars:
    gcp_project: pjds-fog-grouping
    gcp_cred_kind: serviceaccount
    gcp_cred_file: "{{ playbook_dir | dirname }}/credentials/gcp-key-ansible-sa.json"
    zone: "europe-west3-c"
    region: "europe-west3"
#    ansible_ssh_private_key_file: "{{ playbook_dir | dirname }}/credentials/ssh-key-ansible-sa"
  roles:
    - { role: create-instance, vm_names: [ vm-1 ] }

- name: Manage new instances
  hosts: all
  vars:
    ansible_ssh_private_key_file: "{{ playbook_dir | dirname }}/credentials/ssh-key-ansible-sa"
#    ansible_host_key_checking: false
  connection: ssh
  remote_user: sa_110764242531759494195
  become: True
  roles:
    - basic