---
- name: destroy infra
  hosts: localhost
  gather_facts: false
  environment:
    GOOGLE_CREDENTIALS: "{{ credentials_file }}"
  roles:
    - destroy_k8s
    - destroy_network
    - destroy_k8s2
    - destroy_network2
#    - destroy_k8s3
#    - destroy_network3